### ISSUE TITLE
Individuals as MICE

### ISSUE THREAD

**Issue by NuriaQueralt** [CARE-SM/CARE-Semantic-Model#1]
Dear developers,

Cogratulations for the excellent work! 

In the context of representing RD research data on BRAIN, where our individuals are both patients and mice, we are using the CARE-SM semantic model. Reading the CARE-SM wiki, this model is specific for patient data. Do you think it's a problem that we are using it also for representing data from mouse animal models, i.e., where the <Individual> is a mouse?

With kind regards,
Núria

**Comment by pabloalarconm** [comment]
Hi @NuriaQueralt, thats a great question! This question opens a long discussion but I will in a short answer. The model is documented for patient as person, but a different organism could be the subject of the representation. Although some elements are agnostic to the organism studied, this case opens the posibility of defining new/other specific data elements for, in this case, mice.

**Comment by NuriaQueralt** [comment]
Excellent! This is how we are representing it. Thanks tons @pabloalarconm!!!

**Comment by pabloalarconm** [comment]
Absolutely!
