### ISSUE TITLE
RDF models

### ISSUE THREAD

**Issue by NuriaQueralt** [CARE-SM/CARE-Semantic-Model#3]
Dear developers,

In EJP RD we had the models described also in RDF and ShEx. Is this also the case for CARE-SM models? if yes, could you point me at the RDF/ShEx descriptions? 

With kind regads,
Núria

**Comment by pabloalarconm** [comment]
Hi @NuriaQueralt I can add an exemplar RDF/ShEx representation to the repo, Im working on adding this representations now the model looks stable enought.

Thanks for your feedback!
Pablo

**Comment by NuriaQueralt** [comment]
Super thanks @pabloalarconm ! Please, could you let me know when this is ready?
