### ISSUE TITLE
Diagram for Phenotype seems to be wrong

### ISSUE THREAD

**Issue by markwilkinson** [CARE-SM/CARE-Semantic-Model#5]
https://github.com/CARE-SM/CARE-Semantic-Model/wiki/CARE-SM-Symptom

The output node is typed as "observational result" (http://purl.obolibrary.org/obo/NCIT_C70856), in the diagram, and the diagram documentation, it is typed as "phenotype"

**Comment by markwilkinson** [comment]
also... the connection between person and attribute seems to exist in the data, but not in the diagram.

**Comment by pabloalarconm** [comment]
@markwilkinson

Documentation in the wiki were updated. Could you check if its still presence this issue?
